# Generated by Django 5.0.4 on 2024-07-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='attach',
            field=models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d/', verbose_name='添付ファイル'),
        ),
    ]
